version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  init-data-container:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/customers;
      /usr/bin/mc cp /mnt/data/customers.csv minio/customers/customers.csv;
      
      /usr/bin/mc mb minio/organizations;
      /usr/bin/mc cp /mnt/data/organizations.csv minio/organizations/organizations.csv;

      /usr/bin/mc mb minio/people;
      /usr/bin/mc cp /mnt/data/people.csv minio/people/people.csv;
      
       exit 0;
      "
    volumes:
      - ./data:/mnt/data